
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile.workspace
    container_name: php-workspace
    volumes:
      - ../php_project:/var/www/php_project
    stdin_open: true
    tty: true
    restart: unless-stopped

